### ISSUE TITLE
python package install path incorrect

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/PerfFlowAspect#15]
Currently, it appears as though perfflow installs the python bindings to `$PREFIX/lib/python/perfflowaspect`. This should be something more like `$PREFIX/lib/python3.7/site-packages/perfflowaspect`, although some distros want `dist-packages` rather than `site-packages`.  autotools and cmake both have facilities for handling this automatically once we decide on which one we will go with.

**Comment by FrankD412** [comment]
To add to this issue, currently the `setup.py` points to `src/python` -- that will need to be updated. The current install is broken since it was moved to the `src/python` folder directly, but the location of that file depends if you want to have it at the root (the README is suffering from the same issue at the moment).
